//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.08 at 07:17:54 PM CEST 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFGCouncil complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFGCouncil">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="balconyNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nCounsellors" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFGCouncil", propOrder = {
    "balconyNum",
    "nCounsellors"
})
public class CFGCouncil {

    @XmlElement(required = true)
    protected String balconyNum;
    @XmlElement(required = true)
    protected String nCounsellors;

    /**
     * Gets the value of the balconyNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBalconyNum() {
        return balconyNum;
    }

    /**
     * Sets the value of the balconyNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBalconyNum(String value) {
        this.balconyNum = value;
    }

    /**
     * Gets the value of the nCounsellors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNCounsellors() {
        return nCounsellors;
    }

    /**
     * Sets the value of the nCounsellors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNCounsellors(String value) {
        this.nCounsellors = value;
    }

}
