//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.21 at 05:51:35 PM CEST 
//


package jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFGMap complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFGMap">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kingInitLocation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ancestries" type="{urn:co4}CFGAncestries"/>
 *         &lt;element name="region" type="{urn:co4}CFGRegion" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFGMap", propOrder = {
    "kingInitLocation",
    "ancestries",
    "region"
})
public class CFGMap {

    @XmlElement(required = true)
    protected String kingInitLocation;
    @XmlElement(required = true)
    protected CFGAncestries ancestries;
    @XmlElement(required = true)
    protected List<CFGRegion> region;

    /**
     * Gets the value of the kingInitLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKingInitLocation() {
        return kingInitLocation;
    }

    /**
     * Sets the value of the kingInitLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKingInitLocation(String value) {
        this.kingInitLocation = value;
    }

    /**
     * Gets the value of the ancestries property.
     * 
     * @return
     *     possible object is
     *     {@link CFGAncestries }
     *     
     */
    public CFGAncestries getAncestries() {
        return ancestries;
    }

    /**
     * Sets the value of the ancestries property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFGAncestries }
     *     
     */
    public void setAncestries(CFGAncestries value) {
        this.ancestries = value;
    }

    /**
     * Gets the value of the region property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the region property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CFGRegion }
     * 
     * 
     */
    public List<CFGRegion> getRegion() {
        if (region == null) {
            region = new ArrayList<CFGRegion>();
        }
        return this.region;
    }

}
