//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.22 at 07:19:00 PM CEST 
//


package jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CFGPermissionDeck complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CFGPermissionDeck">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="permissionCards" type="{urn:co4}CFGPermissionCards"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CFGPermissionDeck", propOrder = {
    "region",
    "permissionCards"
})
public class CFGPermissionDeck {

    @XmlElement(required = true)
    protected String region;
    @XmlElement(required = true)
    protected CFGPermissionCards permissionCards;

    /**
     * Gets the value of the region property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegion() {
        return region;
    }

    /**
     * Sets the value of the region property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegion(String value) {
        this.region = value;
    }

    /**
     * Gets the value of the permissionCards property.
     * 
     * @return
     *     possible object is
     *     {@link CFGPermissionCards }
     *     
     */
    public CFGPermissionCards getPermissionCards() {
        return permissionCards;
    }

    /**
     * Sets the value of the permissionCards property.
     * 
     * @param value
     *     allowed object is
     *     {@link CFGPermissionCards }
     *     
     */
    public void setPermissionCards(CFGPermissionCards value) {
        this.permissionCards = value;
    }

}
