//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.09 at 01:30:07 PM CEST 
//


package jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Root_QNAME = new QName("urn:co4", "root");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CFGRoot }
     * 
     */
    public CFGRoot createCFGRoot() {
        return new CFGRoot();
    }

    /**
     * Create an instance of {@link CFGPoliticalDeck }
     * 
     */
    public CFGPoliticalDeck createCFGPoliticalDeck() {
        return new CFGPoliticalDeck();
    }

    /**
     * Create an instance of {@link CFGCouncil }
     * 
     */
    public CFGCouncil createCFGCouncil() {
        return new CFGCouncil();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CFGRoot }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:co4", name = "root")
    public JAXBElement<CFGRoot> createRoot(CFGRoot value) {
        return new JAXBElement<CFGRoot>(_Root_QNAME, CFGRoot.class, null, value);
    }

}
