package politicalDeck;

import java.util.Iterator;

public class Garbage extends PoliticalDeck {
	private PoliticalDeck garbage = new PoliticalDeck(); 
	private PoliticalDeck politicalDeck;  //points to the "real" political deck
	//the one generated by Model
	public void refill(PoliticalDeck deck) {
		//Iterator<PoliticalCard> itr = garbage.iterator(); 
	}
	

}
