package politicalDeck;

public class Garbage {
	private PoliticalDeck garbage = new PoliticalDeck(); 
	private PoliticalDeck politicalDeck;  //points to the "real" political deck
	//the one generated by Model
	

}
