package politicalDeck;

import java.util.Random;


public class Hand {
	private PoliticalDeck hand = new PoliticalDeck(); 
	private PoliticalDeck politicalDeck;  //points to the "real" political deck
	//the one generated by Model
	public void drawCard() {
		Random rnd;
		int temp;
		do {
			rnd = new Random(); 
			temp = rnd.nextInt(6);
		} while ( politicalDeck.getDeck().get(temp).getNumCards() == 0 );
		
		politicalDeck.getDeck().get(temp).removeCards();
		hand.getDeck().get(temp).addCards();
	}
	//given the index, it discards a card. No random needed here
	public void discardCard(int index) {
		hand.getDeck().get(index).removeCards();
		politicalDeck.getDeck().get(index).addCards();
		
	}

}
