package politicalDeck;

import java.util.Random;

public class Hand extends PoliticalDeck {
	private PoliticalDeck hand = new PoliticalDeck(); 
	//points to the "real" political deck
	//the one generated by Model
	
	public void drawCard(RealDeck deck) {
		Random rnd;
		int temp;
		do {
			rnd = new Random(); 
			temp = rnd.nextInt(6);
		} while ( deck.getDeck().get(temp).getNumCards() == 0 );
		
		deck.getDeck().get(temp).removeCards();
		hand.getDeck().get(temp).addCards();
	}
	//given the index, it discards a card. No random needed here
	public void discardCard(RealDeck deck, int index) {
		hand.getDeck().get(index).removeCards();
		deck.getDeck().get(index).addCards();
		
	}

}
