package politicalDeck;

public class PoliticalGarbage extends PoliticalDeck {
	private PoliticalDeck garbage = new PoliticalDeck(); 
	private int numColors; 
	//the one generated by Model
	public PoliticalGarbage() {
		
	}
	/**
	 * sets all numCards parameters of deck to zero
	 * useful for refill
	 */
	public void toZero() {
		for(int i=0; i<numColors; i++) {
			//gives numCards for each index
			garbage.getDeck().get(i).setNumCards(0); 
		}
	}
}	

